// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package query

import (
	"context"
)

const add = `-- name: Add :exec
INSERT INTO pinuser (
    user_id
) VALUES (
    $1
)
`

func (q *Queries) Add(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, add, userID)
	return err
}

const getAll = `-- name: GetAll :many
SELECT user_id FROM pinuser
`

func (q *Queries) GetAll(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
